### ISSUE TITLE
Can I fork this for an open-source project ?

### ISSUE THREAD

**Issue by LeoFabre** [JackWithOneEye/StrangeReturns#1]
Hi !
I tested Strange Returns and I really love it !
I am starting an open-source project to build a dub sound system multi-effects module for my control tower, using ELK Audio OS on a Raspberry Pi, and a custom-made open source midi controller for it.

I would love to integrate Strange Returns in the project, and maybe add some features to it if i have the time and learn the skills !

Could you please allow me ? And maybe add a license to this repo ?
My project will be fully open source non-commercial.

Thanks in advance !

Much love and respect,
Leo

**Comment by LeoFabre** [comment]
I've checked out your other plugin Grindr and I would love to use it too ! 😍

**Comment by JackWithOneEye** [comment]
Happy to hear that you have enjoyed using my plugins. I have added a licence to this repo and to Gr**a**indr as well.

**Comment by LeoFabre** [comment]
Amazing ! Thanks a ton ! 🍾🔥
